pipeline:
  id: 40932a82-3ecd-476f-b320-40b128b9a4d5
  name: aoi
  version: 1.0.0
  package_version: 0.0.0.9001
  created_at: 2024-11-27 18:01:50
  last_modified: 2024-11-27 18:01:50
  description: "This pipeline creates a polygon of the study area (AOI) and a raster grid from that polygon using the prc_aoi script."

  # Metadata section providing details about the analysis
  metadata:
    source_name: "Study Area AOI and Raster Grid"    # Name of the analysis
    data_type: "GeoPackage and Raster"              # Types of output data
    file_size: "Variable"                           # Size depends on the study area
    license: "Internal Use Only"                    # License for the outputs
    last_updated: "2024-11-26"                      # Date of creation
    geographic_coverage:                            # Geographical region covered by the AOI
      region: "Study Area"
      bounding_box:                                 # Bounding box coordinates of the AOI
        - -80    # Longitude min
        - 40     # Latitude min
        - -40    # Longitude max
        - 70     # Latitude max
    temporal_coverage:                              # Not applicable for static AOI
      start_date: null
      end_date: null
    variables:                                      # Outputs include spatial variables
      - aoi_polygon
      - raster_grid
    data_quality:                                   # Data quality notes
      - "Generated AOI and raster grid based on provided bounding box."

  # Processing section: Define the analysis step
  processing:
    sources:
      - name: study area aoi
        script: prc_aoi
        input_files: []
        output_files:
          - aoi.gpkg
          - grid.tif

  # Output section: final output of the processed data
  output:
    output_dir: "workspace/data/analyzed/"         # Base directory for the generated data
    log_dir: "workspace/logs/"                     # Directory for logs (optional)
    archive_raw: false                             # No raw data to archive for this analysis
