pipeline:
  id: 56c710c3-1859-4eab-821f-e1e41dbbfd29
  name: neec
  version: 1.0.0
  package_version: 0.0.0.9000
  created_at: 2024-09-20 11:55:13
  last_modified: 2024-09-20 11:55:13
  description: "The National Environmental Emergency Centre (NEEC) provides an inventory of environmental emergencies incidents in Canada. The data requested by the CWS covers notifications impacting or potentially impacting a waterbody in the Atlantic region (including Québec) for the period from 2016 to 2023. A total of 9570 incidents were recorded, but after applying filters such as removing empty coordinates, handling missing date fields, and selecting the greatest quantity for individual spills with multiple substances, 1677 usable observations remain to characterize this pollution threat layer."

  # Metadata section providing details about the data being harvested
  metadata:
    source_name: "Emergencies Incident Notifications from the National Environmental Emergencies Center (NEEC), 2016-2023"  # Name or identifier of the data source
    data_type: "CSV"                                    # Type of data being harvested (e.g., CSV, JSON, Parquet)
    file_size: "N/A"                                    # Approximate size of the file or dataset (not provided)
    license: "Restricted access"             # Dataset license information
    last_updated: "2024-03-15"                          # Timestamp of the last data update
    geographic_coverage:                                # Geographical region covered by the dataset
      region: "Atlantic Region, Canada (including Québec)"
      bounding_box:                                     # Bounding box coordinates of the region (min/max lat/long)
        - -76    # Longitude min
        - -33    # Latitude min
        - 35     # Longitude max
        - 65     # Latitude max
    temporal_coverage:                                  # Time period the dataset covers
      start_date: "2016-01-01"
      end_date: "2023-12-31"
    variables:                                          # List of important variables/columns in the dataset
      - id
      - notification_date_time
      - incident_date_time
      - coordinates
      - incident_name
      - substance_quantity
    data_quality:                                       # Comments on data quality (e.g., missing data, outliers)
      - "Filtered out empty coordinates, records containing 'covid', 'istop', and 'sipps'."
      - "Selected greatest quantity for individual spills with multiple substances."
      - "Removed incidents containing 'mvi' or 'furnace oil'."
      - "Kept all incidents within 1 degree of the coastline."
      - "1677 usable observations out of 9570 incidents."

  # Bibliographic Information
  bibliography:
    - "@TechReport{neec2024,
        title = {Atlantic (Including {{Quebec}}) Notifications Impacting or Potentially Impacting a Waterbody with Select Substances, 2016-2023. {{Extracted}} by {{Philippe Muise}} 2024-01-29.},
        author = {{National Environmental Emergency Centre}},
        year = {2024},
        month = {jan},
        institution = {{Environment and Climate Change Canada}},
      }"

  # Harvest section: Define the sources to download and process
  download:
    sources:                 
      - name: Description of dataset
        source_type: "gcs"
        urls: "cws-private"  
        asset: "NEEC/Description Pollution datasets_2024-02-08.docx"
        credentials: "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json"

      - name: NEEC Incident Fields and Taxonomy
        source_type: "gcs"
        urls: "cws-private"  
        asset: "NEEC/NEEOC Incident Fields and Taxonomy_RR.xlsx"
        credentials: "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json"

      - name: Atlantic NEEC 2024
        source_type: "gcs"
        urls: "cws-private"
        asset: "NEEC/Atlantic NEEC CWS Extraction_2024-01-29.xlsx"
        credentials: "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json"

      - name: NEEC pollution data 2024
        source_type: "gcs"
        urls: "cws-private"
        asset: "NEEC/neec.csv"
        credentials: "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json"

      - name: NEEC pollution data incident fields 2024
        source_type: "gcs"
        urls: "cws-private"
        asset: "NEEC/neec_incident_fields.csv"
        credentials: "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json"

      - name: NEEC pollution data substances 2024
        source_type: "gcs"
        urls: "cws-private"
        asset: "NEEC/neec_substances.csv"
        credentials: "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json"

      - name: NEEC pollution data taxonomy 2024
        source_type: "gcs"
        urls: "cws-private"
        asset: "NEEC/neec_taxonomy.csv"
        credentials: "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json"

  processing:
    sources:
      - name: neec
        script: prc_neec
        input_files: NEEC pollution data 2024
        output_files: neec.csv 

 # Output section: final output of the processed data
  output:
    output_dir: "workspace/data/harvested/"   # Base directory for all downloaded data
    log_dir: "workspace/logs/"                # Directory for logs (optional)
    archive_raw: true                         # Option to archive the raw downloaded data
