pipeline:
  id: 8c0e9e78-0e9a-4329-b8b8-d8a705c11596
  name: viirs_nighttime_light
  version: 1.0.0
  package_version: 0.0.0.9000
  created_at: 2024-11-04 15:38:47
  last_modified: 2024-11-04 15:38:47
  description: "Pipeline to harvest VIIRS Nighttime Light (VNL) monthly data for avg_rade9h, from August to December 2023, using the vcm configuration and j01 platform."

  # Metadata section providing details about the data being harvested
  metadata:
    source_name: "VIIRS Nighttime Light (VNL)"
    data_type: "Raster (GeoTIFF)"
    file_size: "Variable by month"
    license: "Restricted access"                                 
    last_updated: "2024-11-04"
    geographic_coverage:
      region: "Global"
    temporal_coverage:
      start_date: "2023-08-01"
      end_date: "2023-12-31"
    variables:
      - avg_rade9h
    data_quality:
      - "Monthly cloud-free composites; data availability may vary due to cloud cover and polar summer solar illumination."

  bibliography:    
  - "@Dataset{vnl2024,
      author = {{Earth Observation Group, Payne Institute for Public Policy}},
      title = {{VIIRS Night Light (VNL) Dataset}},
      year = {2024},
      url = {https://eogdata.mines.edu/products/vnl/},
      institution = {{Earth Observation Group, Payne Institute for Public Policy}},
      note = {Accessed: 2024-11-21}
    }"
  - "@Article{elvidge2013b,
      author = {Elvidge, Christopher D. and Baugh, Kimberly E. and Zhizhin, Mikhail and Hsu, Feng-Chi},
      title = {{Why VIIRS Data Are Superior to DMSP for Mapping Nighttime Lights}},
      journal = {Asia-Pacific Advanced Network},
      volume = {35},
      pages = {62},
      year = {2013}
    }"
  - "@Article{elvidge2024,
      author = {Elvidge, Christopher D. and Zhizhin, Mikhail and Ghosh, Tathagata and Hsu, Feng-Chi},
      title = {{Annual Time Series of Global VIIRS Nighttime Lights Derived from Monthly Averages: 2012 to 2019}},
      journal = {Remote Sensing},
      status = {In press}
    }"


  # Download section: Specifies how to access the data from the VIIRS server
  download:
    sources:
      - name: VIIRS Monthly Nighttime Light
        source_type: "viirs"
        dataset: "vnl"
        urls: NA
        resolution: "monthly"
        dates:
          - ["2023-08-01", "2023-09-15"]
        file_type: "avg_rade9h"
        config: "vcm"
        platform: "j01"
        credentials: "workspace/credentials/earth_observation_group.json"

  # # Processing (if required)
  # processing:
  #   sources:
  #     - name: vnl_monthly_data
  #       script: prc_vnl_monthly
  #       input_files:
  #         - VIIRS Monthly Nighttime Light
  #       output_files: vnl_monthly_summary.gpkg

  # Output section: final output of the processed data
  output:
    output_dir: "workspace/data/harvested/"
    log_dir: "workspace/logs/"
    archive_raw: true
