pipeline:
  id: d0479151-75ba-451f-9a5b-0d471115ad4f
  name: viirs_night_fire
  version: 1.0.0
  package_version: 0.0.0.9000
  created_at: 2024-11-04 15:45:44
  last_modified: 2024-11-04 15:45:44
  description: "Pipeline to harvest VIIRS Night Fire (VNF) nightly data for December 2023."

  # Metadata section providing details about the data being harvested
  metadata:
    source_name: "VIIRS Night Fire (VNF)"
    data_type: "CSV (point data)"
    file_size: "Variable by night"
    license: "Restricted access"
    last_updated: "2024-11-04"
    geographic_coverage:
      region: "Global"
    temporal_coverage:
      start_date: "2023-12-01"
      end_date: "2023-12-31"
    variables:
      - temperature
      - radiant_heat
      - source_size
    data_quality:
      - "Nightly data available for December 2023 only for the npp platform."

  bibliography:
    - "@Dataset{vnf2024,
        author = {{Earth Observation Group, Payne Institute for Public Policy}},
        title = {{VIIRS Night Fire (VNF) Dataset}},
        year = {2024},
        url = {https://eogdata.mines.edu/products/vnf/},
        institution = {{Earth Observation Group, Payne Institute for Public Policy}},
        note = {Accessed: 2024-11-21}
      }"
    - "@Article{elvidge2013,
        author = {Elvidge, Christopher D. and Zhizhin, Mikhail and Hsu, Feng-Chi and Baugh, Kimberly E.},
        title = {{VIIRS Nightfire: Satellite Pyrometry at Night}},
        journal = {Remote Sensing},
        volume = {5},
        number = {9},
        pages = {4423--4449},
        year = {2013},
        doi = {10.3390/rs5094423}
      }"

  # Download section: Specifies how to access the data from the VIIRS server
  download:
    sources:
      - name: VIIRS Night Fire Nightly Data
        source_type: "viirs"
        urls: NA
        dataset: "vnf"
        resolution: "nightly"
        dates:
          - ["2023-11-01", "2024-12-31"]
        credentials: "workspace/credentials/earth_observation_group.json"

  processing:
    sources:
      - name: VIIRS Night Fire
        script: prc_viirs_night_fire
        input_files:
          - VIIRS Night Fire Nightly Data_files
        output_files: viirs_night_fire.gpkg

  # Output section: final output of the processed data
  output:
    output_dir: "workspace/data/harvested/"
    log_dir: "workspace/logs/"
    archive_raw: true
