---
title: Mapping threats to marine birds to inform conservation and management in Atlantic Canada
fontsize: 12pt
format:
  pdf:
    toc: false
    number_sections: false
    colorlinks: true
  docx:
    toc: false
bibliography: ceacws.bib
csl: ecology.csl
---

<!--
quarto::render('./MetadataS1.qmd')
rmarkdown::render('./FoodWeb-CumulativeImpact.md', output_format = "word_document")
-->

David Beauchesne^1\*^, Kevin Cazelles^1^, Stephanie Avery-Gomm^2^, April Hedd^3^, Philippe Muise^4^, Allison Patterson^5^, Robert Ronconi^5^, Katharine Studholme^6^, Sarah Wong^6^


^1^inSileco, Québec, Canada 

^2^Environment and Climate Change Canada, Ottawa, ON, Canada

^3^Environment and Climate Change Canada, Mount Pearl, Newfoundland and Labrador, Canada

^4^Canada Centre for Mapping and Earth Observation, Canada Centre for Remote Sensing, Ottawa, Ontario, Canada

^5^Environment and Climate Change Canada: Dartmouth, Nova Scotia, Canada

#####

**Abstract**

Coastal and marine birds in Canada face significant threats from anthropogenic activities. Under the Migratory Birds Convention Act (1994) and through the Ocean Protection Plan (OPP) and Marine Spatial Planning (MSP) initiatives, efforts are underway to improve our understanding of the spatiotemporal distribution of these birds and their overlap with threats such as oil spills, vessel traffic, and light pollution. This study presents a comprehensive dataset of spatiotemporal threat layers, integrating a wide range of primary data sources to inform seabird conservation and management within Canada’s Exclusive Economic Zone (EEZ) and beyond.

The dataset comprises secondary-use geospatial threat layers developed from various primary datasets, including open access and proprietary data shared for this project. These layers quantify risks from petroleum pollution, oil and gas infrastructure, vessel activity, and artificial light across the annual cycle of migratory seabirds. Data sources include the Integrated Satellite Tracking of Pollution (ISTOP), National Aerial Surveillance Program (NASP), National Environmental Emergency Centre (NEEC), and Automatic Identification System (AIS) shipping data. Additionally, VIIRS satellite datasets were used to capture artificial light and flaring activity, complemented by regional assessments of offshore wind development from Canada and the United States.

Spatiotemporal threat layers were created through reproducible workflows that integrate historical incident data and geospatial modeling. Petroleum pollution layers, for instance, evaluate the density of oiling events, while vessel disturbance layers quantify the intensity of ship traffic and associated risks. All datasets were processed into a 1-$km^2$ resolution study grid covering Canada’s EEZ, using the WGS84 coordinate reference system (EPSG:4326). The resulting data products are stored as Cloud Optimized GeoTIFFs (COGs), with comprehensive metadata documenting workflows and processing details. The datasets and associated code are openly accessible via Zenodo at https://doi.org/TO/ADD and https://doi.org/TO/ADD, and the codebase is also available on GitHub (https://github.com/inSilecoInc/ceacws).

This work does not generate new primary data but instead integrates diverse datasets to produce secondary-use geospatial threat layers, addressing critical gaps in marine bird conservation. Applications of these data include informing environmental response planning, supporting recovery strategies for at-risk species, and enhancing marine spatial planning to mitigate threats. For example, this work provides a foundation for evaluating cumulative effects on vulnerable species, such as the Leach’s Storm-Petrel, which regularly forages beyond Canada’s jurisdiction. By aligning with Canada’s OPP and MSP frameworks, this dataset contributes to sustainable ocean management and facilitates evidence-based decision-making to safeguard Canada’s coastal and marine bird populations.

**Current word count**: ***408*** of a potential ***500*** words

#####

*Key words/phrases:* 
Annual cycle,
Light,
Petroleum activities,
Petroleum pollution,
Marine birds,
Marine threats,
Shipping,
Wind farms

#####

Open Research: Data is available in Zenodo at https://doi.org/TO/ADD. 
Code is available in Zenodo at https://doi.org/TO/ADD.

#####

*Corresponding Author E-mail: david.beauchesne@insileco.io


#

##### Affiliations details (*to remove once validated*)

- David Beauchesne
  - david.beauchesne@insileco.io
  - inSileco, Québec, Canada
  - ORCID: 0000-0002-3590-8161
- Kevin Cazelles
  - kevin.cazelles@insileco.io  
  - inSileco, Québec, Canada
  - ORCID: 0000-0001-6619-9874
- Stephanie Avery-Gomm
  - Stephanie.Avery-Gomm@ec.gc.ca
  - Environment and Climate Change Canada, Ottawa, ON, Canada
  - ORCID: 0000-0003-2882-0978
- April Hedd
  - April.Hedd@ec.gc.ca
  - Environment and Climate Change Canada, Mount Pearl, Newfoundland and Labrador, Canada
  - ORCID: 0000-0003-2222-2627
- Philippe Muise
  - Philippe.Muise@ec.gc.ca
  - Canada Centre for Mapping and Earth Observation, Canada Centre for Remote Sensing, Ottawa, Ontario, Canada
- Allison Patterson
  - Allison.Patterson@ec.gc.ca
  - Environment and Climate Change Canada: Dartmouth, Nova Scotia, Canada
  - ORCID: 0000-0001-9931-2693
- Robert Ronconi
  - Robert.Ronconi@ec.gc.ca
  - Environment and Climate Change Canada: Dartmouth, Nova Scotia, Canada
  - ORCID: 0000-0002-3635-7162
- Katharine Studholme
  - Katharine.Studholme@ec.gc.ca
  - Environment and Climate Change Canada: Dartmouth, Nova Scotia, Canada
  - ORCID: 0000-0003-0921-4745
- Sarah Wong
  - sarah.wong2@ec.gc.ca
  - Environment and Climate Change Canada: Dartmouth, Nova Scotia, Canada
