project:
  type: book
  output-dir: ../../docs/report

book:
  title: Mapping threats at sea to marine birds throughout their annual cycle to inform conservation and management in Atlantic Canada
  subtitle: Progress report
  author: 
    - name: David Beauchesne
      degrees: PhD
    - name: Kevin Cazelles
      degrees: PhD
    - name: Steve Vissault
      degrees: MSc
  chapters:
    - index.qmd
    - 1_shipping.qmd
    - 2_petroleum.qmd
    - 3_references.qmd

bibliography: references.bib
csl: frontiers.csl

format:
  html:
    theme: cosmo