---
title: "Shipping-based pollution"
---

## Tasks

1. Access to shipping AIS data through Global Fishing Watch
2. Prepare monthly petroleum pollution and disturbance due to vessel traffic threat layers in the Atlantic Ocean
   1. All vessels
   2. Cargo/bulk vessels
   3. Fishing vessels

## Global Fishing Watch

The purpose of Global Fishing Watch is to create and publicly share knowledge about human activity at sea to enable fair and sustainable use of our ocean. They use cutting-edge technology to turn big data into actionable information. They believe human activity at sea should be common knowledge in order to safeguard the global ocean for the good of all. Global Fishing Watch’s open-access technology products, datasets, and code accelerate research and innovation and support sustainable ocean management. They offer a variety of products related to human activity at sea, including shipping and fisheries, but also data on ocean conditions and biology. Access to their data can be achieved through their [API](https://globalfishingwatch.org/our-apis/), which is also accessible through an R Package called [`gfwr`](https://github.com/GlobalFishingWatch/gfwr). 

The `gfwr` R package offers wrapper functions to access data through the GFW APIs. It provides convenient functions to freely pull GFW data directly into R in tidy formats. The package currently works with the following APIs:

- [Vessels API](https://globalfishingwatch.org/our-apis/documentation#vessels-api): vessel search and identity based on AIS self-reported data
- [Events API](https://globalfishingwatch.org/our-apis/documentation#events-api): encounters, loitering, port visits and fishing events based on AIS data
- [Map Visualization (4Wings API](https://globalfishingwatch.org/our-apis/documentation#map-visualization-4wings-api): apparent fishing effort based on AIS data

The incentive of fetching data from such an API is that the current project could have been built so that continuous integration of new data could be performed, ensuring an updated assessment of this particular threat layer through time. However, after exploring the APIs and contacting representatives of GFW, we had to come to the conclusion that the data needed for this project were not and would likely not be available through their API. They stated that other products that might be useful are planned to be released in the future, such as vessel presence raster resources. However, the release dates for these resources extends beyond the timelines of the current project. We therefore had to pivot to an alternative data source to complete this part of the contract.

## Vessel Density Mapping

During the same timeframe of this project, @veinot2023 published a Technical Report detailing a project seeking to map vessel density in the Northwest Atlantic in 2019 using Automatic Identification System (AIS) data. Their work covers our study area, but was not available publicly yet. Since, their work has been extended to include vessel density mapping for the years 2013 through 2022 and has been made public on the Open Government data platform as a series entitled [*Vessel Density Mapping Series in the Northwest Atlantic*](https://open.canada.ca/data/en/dataset/e60a7e32-5a67-45d6-900d-e6ab6b581a51). These data provide vessel density raster layers monthly for all vessel types combined, and yearly for different vessel types. This does not match perfectly with the requirements for this project. Namely, we would need to differentiate between daytime and nighttime vessel traffic, and use monthly data for each vessel type. In light of this, we agreed on a strategy to address this issue. 

First, we built the code necessary to access the openly available data and integrate it in our study grid.; this data serves as an acceptable backup plan in case we cannot access more detailed data. The [code](https://github.com/inSilecoInc/ceacws/blob/main/project-data/pipedat/vessel_density_mapping_dfo-98916b4a/vessel_density_mapping_dfo-98916b4a.R) that fetches the data from the Open Government platform and integrates it in our study grid has therefore been developed and is available in the *research compendium*.

Second, the team from the CWS contacted the authors of @veinot2023 to discuss the possibility of either accessing the raw AIS data that they used to generate their own vessel density mapping, collaborating on a refined version of their work that addresses the needs of the CWS, or a combination of both. After discussing with their team, it was agreed that we would meet with a representative from their team to discuss the approach that they used to prepare their vessel density layers and potentially collaborate on updating their code to generate the layers that are required for this project. It was also agreed that the Northwest Atlantic region track lines and AIS data points, with MMSI data and times could be shared with us, under condition of a signed agreement and the transfer of anonymized MMSI numbers to ensure confidentiality. The data were transferred to the CWS on March 20th and we are currently waiting to have access to continue with our work. The threat layers using shipping data will therefore be completed during the second part of this project. 

## Notes & references
